//go:build linux

package runtime

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"github.com/cilium/ebpf/ringbuf"
)

func StartGuard() {
	// 1. Allow the application to lock memory for eBPF resources
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// 2. Load the compiled eBPF objects (Generated by bpf2go)
	var objs bpfObjects
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	// 3. Attach the Hook to the Kernel Tracepoint
	kp, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExecve, nil)
	if err != nil {
		log.Fatalf("opening tracepoint: %v", err)
	}
	defer kp.Close()

	// 4. Open the RingBuffer (The data pipe)
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %v", err)
	}
	defer rd.Close()

	log.Println("🛡️  KIDON GUARD ACTIVE (Runtime Protection Enabled)")
	log.Println("Waiting for events... (Try running 'bash' to test)")

	// 5. Loop forever reading events
	go func() {
		for {
			record, err := rd.Read()
			if err != nil {
				if err == ringbuf.ErrClosed {
					return
				}
				log.Printf("read error: %v", err)
				continue
			}

			// Parse the binary data back into a struct
			// Note: For MVP, just log the raw event
			_ = record
			log.Printf("🚨 ALERT: BLOCKED SUSPICIOUS PROCESS EXECUTION!")
		}
	}()

	// Wait for CTRL+C to exit
	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)
	<-stopper
}
