//go:build linux

package runtime

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
	"github.com/cilium/ebpf/ringbuf"
)

// GuardMode specifies which protection to enable
type GuardMode int

const (
	GuardModeProcess GuardMode = 1 << iota // Process execution monitoring
	GuardModeNetwork                        // Network egress filtering
	GuardModeAll     = GuardModeProcess | GuardModeNetwork
)

// StartGuard launches the process execution monitor (legacy v0.1.0)
func StartGuard() {
	StartGuardWithMode(GuardModeProcess)
}

// StartNetworkGuard launches only the network guard (v0.2.0)
func StartNetworkGuard(cgroupPath string) {
	ng := NewNetworkGuard()
	ng.LoadDefaultPolicy()
	
	if err := ng.Start(cgroupPath); err != nil {
		log.Fatalf("Failed to start network guard: %v", err)
	}
	defer ng.Close()
	
	ng.MonitorEvents()
}

// StartFullGuard launches both process and network guards (v0.2.0)
func StartFullGuard(cgroupPath string) {
	// Start network guard in background
	ng := NewNetworkGuard()
	ng.LoadDefaultPolicy()
	
	if err := ng.Start(cgroupPath); err != nil {
		log.Printf("⚠️  Network guard failed to start: %v", err)
		log.Println("Continuing with process guard only...")
	} else {
		defer ng.Close()
		go ng.MonitorEvents()
	}
	
	// Start process guard
	StartGuardWithMode(GuardModeProcess)
}

// StartGuardWithMode launches guard with specified mode
func StartGuardWithMode(mode GuardMode) {
	// 1. Allow the application to lock memory for eBPF resources
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// 2. Load the compiled eBPF objects (Generated by bpf2go)
	var objs bpfObjects
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	// 3. Attach the Hook to the Kernel Tracepoint
	kp, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExecve, nil)
	if err != nil {
		log.Fatalf("opening tracepoint: %v", err)
	}
	defer kp.Close()

	// 4. Open the RingBuffer (The data pipe)
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %v", err)
	}
	defer rd.Close()

	log.Println("🛡️  KIDON GUARD ACTIVE (Runtime Protection Enabled)")
	log.Println("Waiting for events... (Try running 'bash' to test)")

	// 5. Loop forever reading events
	go func() {
		for {
			record, err := rd.Read()
			if err != nil {
				if err == ringbuf.ErrClosed {
					return
				}
				log.Printf("read error: %v", err)
				continue
			}

			// Parse the binary data back into a struct
			_ = record
			log.Printf("🚨 ALERT: BLOCKED SUSPICIOUS PROCESS EXECUTION!")
		}
	}()

	// Wait for CTRL+C to exit
	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)
	<-stopper
}
